- LICENSE
Considered a CC license, but using the same license as for all other SciPy
code and documentation seems more appropriate.  Also less of an issue when
copying code/examples into an article.
> DOC: add 3-clause BSD license.

- scipy-1.0/paper.tex
- scipy-1.0/references.bib
The recently-adopted Governance and Code of Conduct Documents are mentioned in the proposed manuscript outline; I've tried to draft a summary of the recently-adopted docs in this PR. I think @rgommers was slotted to draft this subsection, so please do criticize here! Just trying to keep things moving.
Maybe we can cite the respective documents a bit more "formally" than I have at the moment (I just used the pull request numbers for now) & perhaps the same for the Codes of Conduct from other communities that inspired us (only mentioned by popular name at the moment).
> Drafted a short governance section

- scipy-1.0/paper.tex
- scipy-1.0/references.bib
Attempt to address @rgommers [comment](https://github.com/scipy/scipy-articles/pull/28#discussion_r198720893) for this subsection re: SciPy not currently having a journal publication & also add proper references for some of the prominent journal articles that cite usage of the SciPy library.
> Clarify / add some references for Impact Now subsection

- scipy-1.0/paper.tex
I've drafted a title for the manuscript and added the steering committee members to the author list; I've also added the contributors to the paper so far if they weren't already included in the latter list. 
This somewhat circumvents the originally-described detailed procedure for authorship assignments, but hopefully isn't too controversial and helps us continue to move forward. Nothing in particular is meant by the current ordering of authors; I suppose people should start adding themselves / their affiliations when they next open a PR etc.
> ENH: add some authors and a title for manuscript

- scipy-1.0/ckdtree.tex
- scipy-1.0/references.bib
I found a few (hopefully) pertinent references by digging through the literature. I don't actually see any citations directly associated with the dictionary of keys sparse matrix approach, but I did find previously-published work that confirms the merit of using a hash-table data structure for constructing a sparse matrix. Amazingly, wikipedia cites the SciPy implementation of dictionary of keys sparse matrix and nothing else for "dok sparse matrices."
Anyway, hopefully this is a sensible start for this tech improvements section.
> Drafted ckdtree sparse distance matrix section

- scipy-1.0/paper.tex
- scipy-1.0/references.bib
I know that citations for other packages are missing, I want to leave that out for now. @jarrodmillman already has a bunch in his BibTeX file, and we can go through at the end for consistent citing.
> Add a section on the scope of SciPy

- scipy-1.0/paper.tex
- scipy-1.0/references.bib
Though I'm (really) not the person to draft the stats 'recent technical improvements' section, sometimes it is helpful to have a starting skeleton for the experts to chip away at / improve (or direct me to make changes).
My strategy for compiling this section, since I only occasionally review stats PRs, was to parse the changelogs for scipy.stats over the last few releases and just look for i.e., major additions or design changes.
For a start I tried to parse the logs back through 0.17, but not 0.16 (yet--depending on how much we want in here).
> Add section on stats distributions

- scipy-1.0/paper.tex
- scipy-1.0/references.bib
I read through the recent community-focused [astropy manuscript](http://iopscience.iop.org/article/10.3847/1538-3881/aabc4f) and thought it might be suitable to at least cite them in a community-related section of our paper.
There are common authors on both projects (and I'm not one, so that removes some bias), and I think there has been some decent exchange of ideas / things that worked well between the two connected communities.
They cite NumPy and SciPy as building blocks in their manuscript, and several conference proceedings where @stefanv and @jarrodmillman were editors, etc., so community connection.
A *specific* example of transfer back to SciPy, if there is one that comes to mind, might make this more compelling if others think it is a good idea--this may not be the right …
> Cite astropy in broader community section draft

- scipy-1.0/paper.tex
- scipy-1.0/references.bib
Add a citation for the [linguist library](https://github.com/github/linguist), which is a task described in #65.
I didn't see any Zenodo DOIs on their releases, etc., so simply citing their GitHub page.
> Add linguist citation

- scipy-1.0/paper.tex
- scipy-1.0/references.bib
Checklist item from #65 -- adding a recent citation for Project Jupyter was a reviewer request for the SymPy paper as noted [here](https://github.com/jupyter/jupyter/issues/190), and the preferred citation as of the late 2018 discussion in that GitHub issue is added in this PR.
> Add Project Jupyter citation / reference

- scipy-1.0/paper.tex
- scipy-1.0/references.bib
Checklist item from #65.
- VTK is actually associated with `Kitware`, and ownership actually appears to remain with the original authors who wrote code in spare time while working at GE before forming `Kitware`.
- cite the preferred (textbook) source according to [VTK about page](https://vtk.org/about/)
> Correct company & preferred citation for VTK

- scipy-1.0/paper.tex
For checklist item in #65:
- Current status (maturity, users) subsection
- this subsection looks messy / undeveloped with question marks and ellipses & then just mentioning the timeline figure which isn't even cited in LaTeX
Also, I think Ralf mentioned he was "ok" with the paper stopping at 1.0 (that's kind of the point, I guess), rather than getting into `1.1`, `1.2`, and the latest stuff.
> Clean up Current Status subsection

- scipy-1.0/paper.tex
- scipy-1.0/references.bib
Checklist item from #65 -- *Scientific Reports* prohibits footnotes, so use proper references instead.
We're now over double the suggested cap reference count:
> As a guideline references should be limited to 60 (this is not strictly enforced).
But let's deal with that if / when it becomes an issue. This is representing a big body of work / history, after all.
> Convert footnotes to proper references

- scipy-1.0/paper.tex
- scipy-1.0/references.bib
Targeting the following checklist items from #65:
- Benchmark suite
- the "see above" comment re: unit tests may now be below? 
- shouldn't the "python run.py" command just be "asv run"? maybe it was supposed to be runtests.py or the custom SciPy handler, but using asv directly is probably preferred anyway
- "the documentation" should probably be "the asv documentation" in last paragraph
> Benchmark section revisions

- scipy-1.0/paper.tex
Checklist item from #65.
Just fill in the first year that SciPy US conference had multiple tracks, which was previously just a set of ellipses. That said, this information is a little redundant with previous sentence.
Looks like student sponsorship & proceedings preceded the multi-track format based on schedules available at https://conference.scipy.org/past.html
> Fill in first year US SciPy had > 1 track

- scipy-1.0/paper.tex
- scipy-1.0/references.bib
Aims to resolve the following checklist items from #65 related to Project Scope subsection:
- "...SciPy provides what one expect to find..."
- cite the other projects mentioned in this sentence, at least if they haven't already been cited before in the paper
- "expects"
- the sentence is then abruptly followed with an unlabeled list, and this needs to be cleaned up
> Project Scope cleanup / improvement

- scipy-1.0/paper.tex
For checklist items from #65:
- Future development
- Condense the PyData sparse content a little maybe & update if appropriate given any recent roadmap / plan adjustments?
- there is nothing else in this section -- perhaps just refer back to the roadmap then, or combine roadmap and future directions somehow??
I think the easiest solution here is to remove the "Future Development" section--it is redundant with the preceding "Roadmap" section, which already correctly mentions Hameer's sparse package.
Roadmap section may need updates, but on the other hand we would technically be referring to the roadmap from 1.0 instead of *now*, so just a short table citing the real thing may suffice there anyway (separate checklist item).
> Move Roadmap into Future Work subsection

- scipy-1.0/paper.tex
- scipy-1.0/references.bib
Fixes #88.
Cite the GitHub article for SciPy impact on machine learning community in abstract + appropriate section of manuscript.
> Cite SciPy impact on machine learning from GitHub report

- scipy-1.0/paper.tex
For checklist item from #65:
> Common Infrastructure
This subsection is blank -- do we want to keep it?
This PR proposes removing it. Alternatively, we could shift to supporting information, but only if someone is proposing specific content or willing to write it.
> Remove common infra change subsection

- scipy-1.0/paper.tex
- scipy-1.0/references.bib
For checklist item in #65:
> Maintainers and contributors
citation / link for SciPy Developer Guide maybe
It is hardly desirable to add more citations, and if that is the decision we can close this and check off the item. Otherwise, this directs the reader to our dev guide for contributing.
> Cite SciPy Developer Guide

- scipy-1.0/ckdtree.tex
Meant to address checklist item from #65:
> There's a TODO-style sentence in this section with "Add a Figure to show the scaling, before and after. perhaps give an example or some formula. (cite / mention faster implementions of paircounting algorithms / treecorr, corrfunc)"
This PR proposes to remove that TODO-style content, and we're already providing the correct citation for the main algorithm if the reader wants to explore the literature in greater detail. The docstring for `cKDTree` also contains citations for example applications and example formula, etc. Plus Figure 4 is actually already a cKDtree performance improvement plot.
Alternatively, the content could be moved to the supporting information and filled in there, but unless someone wants to do that very soon, I suggest just …
> Remove extraneous content near end of KDTree section

- scipy-1.0/ckdtree.tex
- scipy-1.0/references.bib
Checklist item from #65:
> sentence starting "The cKDTree module implements a dual tree counting algorithm..." is a bit sudden / list-like
Specific improvements include dates / PR links for feature additions to clarify what is actually new, and usage of the actual function / method name for clarity. We could also add `d0afcaf6a` for the initial addition of `count_neighbors`, though I've just added the year for that since it is not a recent improvement. The `cKDTree` docstring is consistent with the primary literature citation originally used, so that should be okay. The use of that algorithm is described as "loose," but good enough I think.
> Improvements to cKDTree paragraph 4

- scipy-1.0/paper.tex
- scipy-1.0/scipy-optimize.tex
For checklist items from #65:
> - **Nonlinear optimization**
>    - **Local**
> - [ ] Table 1 is nice; the sentence citing it should mention that it includes some of the more recent additions since we're still in the umbrella of key / recent technical improvements
> - [ ] that said, Table 1 also includes additions from as far back as SciPy 0.6 -- which is a longer time span than "last 3 years" for the improvements section as a whole...
>    -  [ ] what about i.e., a dashed vertical line / highlight of some sort dividing "last 3 years" and "before that" in the Table?
>  - [ ] The Table caption is very detailed, but I'm a little concerned about its size -- could we cut it down a bit and move some of the heavy details to i.e., supporting information?
The approach drafted in this PR cuts the …
> Table 1 (optimization) concision / recent changes adjustments

- scipy-1.0/paper.tex
- scipy-1.0/scipy-optimize.tex
- scipy-1.0/subpackages.tex
For checklist item from #65:
> **Numerical optimization**
> * [ ]  I suspect we should remove the background on what scipy.optimize does with the list of 7 problems -- we should find a way to make this relatively clear & abstract that information to earlier in the paper when the 16 SciPy submodules are described
This PR proposes to fix the issue by moving the longer background content to the SI & citing that SI content from the subpackages description earlier in the manuscript.
cc @antonior92 
There are more simplifications to the optimize section suggested in the checklist for the purpose of concision, but I'll start with this one for now.
> Shift optimize background content for concision of main text

- scipy-1.0/paper.tex
The roadmap description for `ndimage` recently changed: https://scipy.github.io/devdocs/roadmap-detailed.html
Updated the paper summary accordingly.
> Change roadmap summary of ndimage

- scipy-1.0/paper.tex
Mostly stylization (capitalization, teletype) fixes.
Also added detailed caption to figure proposed in #99.
Please consider:
- "with the `pytest` runner" -> "with the `pytest` framework" (or do we mean "with `pytest-runner`"?)
- moving the line "Some of the historical components of the codebase would still benefit from increased test coverage." to the discussion, when it is written
> Test suite

- scipy-1.0/paper.tex
Minor grammatical edits.
If we want to keep all the current content, which is a fine but substantial (~467 word) summary of the governance document and Code of Conduct, I have other suggestions. But do we have space for all of this content?
Here is a reduced version to consider (~215 words).
---
SciPy adopted an official Governance Document on August 3, 2017\cite{SciPyProjectGovernance}.  A Steering Council, currently composed of 18 members, oversees daily development of the project by contributing code and reviewing contributions from the community. Council Members have commit rights to the project repository, but they are expected to merge changes only when there are no substantive community objections. The Chair of the Steering Council, Ralf Gommers, is responsible for initiating …
> Project organization - Governance

- scipy-1.0/paper.tex
Minimal changes.
Other suggestions I can put in this PR if they sound like a good idea:
1. The "Governance" and "Maintainers and contributors" subsections are focused on SciPy itself (internal). "Commmunity beyond the SciPy library" is about relationships with other projects (external), but its sandwiched between the other two internal sections. I would suggest making the order "Governance", "Maintainers and contributors", and "Community beyond the SciPy library".
2. This "Project organization and community" section is all about how the SciPy project works. The "Governance" subsection is about the official leadership roles, like the government of a city. The "Maintainers and contributors" subsection is about the people, like the citizens. The "Community beyond the SciPy library" …
> Community beyond

- scipy-1.0/paper.tex
We're not allowed to have subheadings in the discussion, so I removed them. I also removed the 20,000 visitors figure from SciPy Today, as the same figure appeared in this section.
There are a few remaining issues. 
1. We mention LIGO here for a second time. It probably needs to be removed.
2. I think the example Cython syntax should be removed. 
3. We can resurrect the fact that the test suite is in good shape but that vendored code could use better test coverage.
Also consider 4) whether we need to rework the discussion section more substantially. The concern is that a discussion should analyze and interpret what has already been presented, whereas right now half of the discussion is a collection of new facts.
In any case, 5) do we also want some sort of Conclusion section? Right now …
> Discussion

- scipy-1.0/paper.tex
- scipy-1.0/poly.tex
changed "code base" to "codebase" (only) for consistency
"b-spline" to "B-spline according to common convention
Removed ' from ABI's, as some would argue that it is inappropriate
remove inappropriate colon
removed inappropriate comma
Inserted comma after introductory phrase
define COO and DIA
> Technical Improvements punctuation, consistency, convention

- scipy-1.0/ckdtree.tex
- scipy-1.0/paper.tex
There were duplicate definitions of CSR/CSC format acronyms in adjacent sections sparse and cKDTree. The sparse section seemed a more natural place to define them than right before it in cKDTree, so I swapped the order and removed the duplicate definitions from cKDTree.
(Note: COO and DIA definitions added to sparse in #129)
> Sparse / cKDTree tweaks

- scipy-1.0/paper.tex
Moved benchmark suite after test suite because benchmark suite section refers to unit test suite section. Easier for reader to remember the previous paragraph than look ahead. Also a few stylization fixes.
Please consider:
1. removing 1) the command to generate the figure (or moving it into the caption) and 2) and the material after the figure about how to use `asv`. To me it seemed like a short tutorial on how to use `asv` with SciPy, which seemed out of place. If the intent is to advertise the ease of generating such results - which is a great new feature - a description of the capabilities of the `run` script would work
2. removing the last part of "allows us to objectively measure that our code base is improving~~, to empower scientific applications.~~"
3. rewording "generally remains …
> Benchmark Suite

- scipy-1.0/paper.tex
Moved from #117.
Removed the command to generate the figure. As #117 records, it doesn't "just work", so I don't think it's worth including.
Removed the material after the figure about how to use asv. To me it seemed like a short tutorial on how to use asv with SciPy, which seemed out of place.
Removed the last part of "allows us to objectively measure that our code base is improving~~, to empower scientific applications.~~"
Reworded "generally remains constant or improves over the commit hash history of the project" -> "improves over time."
Reworded "the performance of the SciPy codebase was monitored with asv starting in" -> "the performance of the SciPy codebase has been monitored with asv since"
Moved the thought "in addition to ensuring that unit tests are passing" to the beginning …
> Tightened Benchmark suite section

- scipy-1.0/paper.tex
The "Governance" and "Maintainers and contributors" subsections are focused on SciPy itself (internal). "Commmunity beyond the SciPy library" is about relationships with other projects (external), but its sandwiched between the other two internal sections. I simply changed the order of subsections to "Governance", "Maintainers and contributors", and "Community beyond the SciPy library"; they are now in order from closest to the core of the project to further away.
> Swap subsections in Project Organization

- scipy-1.0/paper.tex
Starting from discussion on #122
As far as I can see, the message this paragraph is trying to convey is that the communities of downstream projects actively contribute to scipy and by doing so indirectly contibute to other projects. Thus, scipy plays a mediator and meeting point role in the python ecosystem.
I don't dislike the current title, but I see @mdhaber point about more specific title and I don't mind changing it. What about "Relation with sibiling projects"?
> Community beyond the SciPy library section

- scipy-1.0/paper.tex
- scipy-1.0/references.bib
Added citations to software named in "SciPy Begins" section.
Closes #112 
Note that we cite the Numeric manual in the paragraph above, so I didn't cite Numeric again in this section.  LMK if I should add that.
> Added citations to SciPy begins

- scipy-1.0/ckdtree.tex
- scipy-1.0/paper.tex
- scipy-1.0/poly.tex
- scipy-1.0/references.bib
- scipy-1.0/subpackages.tex
Fixes minor punctuation and reference issues.
Something I wasn't able to correct: is there a reference for DFITPACK? 
_Update: I guess not. https://mail.python.org/pipermail/scipy-user/2010-July/026230.html_
I added some references to the list:
```
MATLAB\cite{matlab}, IDL, Matrix Market\cite{boisvert1997matrix}, Fortran, NetCDF\cite{rew1990netcdf},
Harwell-Boeing\cite{harwellboeing}, WAV and ARFF data files
```
Could argue that for a consistent citation policy some more would need to be added or removed.
> Minor punctuation/reference fixes

- scipy-1.0/paper.tex
Pretty self-explanatory. My institute recently changed names. This uses the updated name.
> Update affiliation since ICES changed its name recently.

- scipy-1.0/paper.tex
Sometimes academic customs change and last author means a different thing. So please let me know if this is the wrong place, I have absolutely no preference about the order.
> Added my name to authors list

- scipy-1.0/paper.tex
For consideration. I don't have a problem with short tables, but [Scientific Reports does](https://www.nature.com/srep/publish/guidelines#general-figure). 
Closes #165.
>  Removed language breakdown table

- scipy-1.0/core-dev.tex
It seems that two researchers from Google but different offices are authors in this paper, and I was erroneously attached to the Cambridge address. I took the approach of creating a new entry for me, changing the Cambridge address to Montreal. It would also be fine for me to remove geographical information and have as affiliation simply Google LLC for both me and Paul van Mulbregt (but I would need to check with Paul first).
Also corrected Google Inc. (old affiliation) to Google LLC
> Correct my affiliation (I'm based in Montreal, not Cambridge)

- scipy-1.0/paper.tex
- scipy-1.0/scipy-optimize.tex
- Fix typo.
- Consistently spell "tool stack".
- Use Apple's capitalization of macOS.
> Small fixes.

- scipy-1.0/paper.tex
Thanks @stsievert for catching this in #180
> Python matrix multiplication operator font fix

- scipy-1.0/paper.tex
Fixes #225 
* address reviewer comment from *Nature Methods* requesting
a brief description of GitHub prior to its first usage
in the text
It also occurs to me that it might be useful to use a LaTeX highlighting markup for the requested changes so that we could optionally compile a PDF with / without the highlighted changes. Maybe that's too complicated, but could save time for the person ultimately submitting the revised doc along with rebuttal.
> MAINT: review comment re: GitHub

- scipy-1.0/paper.tex
- scipy-1.0/references.bib
Close #227 
First commit is just line break adjustments.
Second commit adds a sentence to introduce continuous integration.
This was an attempt to introduce CI without making any changes to surrounding text. Not sure whether it all fits together in the best way, but I think it addresses the comment.
> Introduce Continuous integration

- .gitignore
- scipy-1.0/paper.tex
Partially addresses #222.
While I wish we could include the entire background section, here I've tried to streamline the SciPy Begins section. Please see self-review for rationale.
This might fully address #222, actually. There aren't large swaths in the rest of the background that I'd consider removing, except maybe the paragraph about NumFOCUS.
> Streamline SciPy Begins section

- scipy-1.0/paper.tex
Partially addresses #222 
The main idea of this paragraph - that the introduction of Numeric led to the growth in the number of scientific packages, many of which were written by students - is captured in the first paragraph of the next section, SciPy Begins. The previous paragraph includes the idea that it was nice to add domain-specific functionality to a general purpose language rather than the other way around.
> Removed paragraph before SciPy Begins

- scipy-1.0/paper.tex
Partially addresses #222 
It's not really part of the history of SciPy 1.0.
> Removed paragraph about founding of NumFocus

- scipy-1.0/paper.tex
Fixes #220 
* both *Nature Methods* reviewers requested clarification
regarding SciPy's stance on staying relevant with GPUs
and distributed computing
* briefly mention that while these were out of scope
at the 1.0 release point, we now have an explicit
example of experimental GPU backend support in `scipy.fft`,
to be detailed in a future report
~We actually stopped testing PyPy on master, so that's a slightly awkward edit.~ This is no doubt contentious, but anyway let's make an effort and try to get it published soon :)
> MAINT: reviewer comment re: GPUs, etc.

- scipy-1.0/paper.tex
Fixes #252 to move the CI definition prior to the first mention of CI in a Figure, as per reviewer comment.
While the CI definition may be slightly out of place at that point of the article, I'd say checking off the box to satisfy the reviewer comment is more important that some kind of ideal / flawless flow to the paper with all testing content confined to the testing section.
> MAINT: move CI definition
