.circleci/config.yml
.gitignore
scipy-1.0/Makefile
scipy-1.0/paper.tex

Working on gh-8. Still need to hook things up to a CI, but it seems worthwhile to let people comment on the makefile first.

Makefile for SciPy 1.0 paper

---

scipy-1.0/paper.tex
scipy-1.0/references.bib
scipy-1.0/scipy-optimize.tex

Still don't know what I'm doing with git. Just trying to figure out how to add my contributions to the paper.
I'd appreciate feedback to any questions asked in the text.

[WIP] ENH: Optimize Section

---

scipy-1.0/paper.tex
scipy-1.0/references.bib
scipy-1.0/subpackages.tex

This is the content that I suggested adding in
https://github.com/scipy/scipy-articles/issues/9#issuecomment-375089042

Add a brief description of each subpackage in scipy.

---

scipy-1.0/paper.tex

Suggested in https://github.com/scipy/scipy-articles/issues/19#issuecomment-380520085

MAINT: add paragraph on `asv continuous`

---

scipy-1.0/paper.tex

Added a small subsection covering the test suite; I'm probably missing some details, but it is a start.

ENH: add draft of test suite section.

---

scipy-1.0/paper.tex

The manuscript outline contains a subsection in the Discussion or Conclusions titled "impact now." I've tried to draft two small paragraphs about this, but we'll probably want more robust citation metrics & so on so it just to get the ball rolling. I still need to add some proper references here and there too.
I bet some of the long-time community members will have some more compelling use examples for SciPy or unusually important publications that use it as a foundation. 
Also probably have to be cautious of usage stats where i.e., continuous integration "clones" are counted, and so on.

[WIP] "Impact now" subsection

---

scipy-1.0/ckdtree.tex
scipy-1.0/paper.tex

I am starting to write down the things that I can think of. 
@sturlamolden I'll add you to the repo such that you can directly push into the PR.

WIP: Add stub / brainstorms for the cKDTree module.

---

scipy-1.0/paper.tex

First draft of a subsection about `LowLevelCallable`, which is mentioned in the proposed manuscript outline. Not my area of expertise, but just trying to keep things moving--feel free to request a substantial rewrite. I guess a code example might be more compelling here, but I'm not sure if we were really wanting to have code snippets in the ms.

Drafted a subsection for LowLevelCallable

---

scipy-1.0/paper.tex

I drafted an abstract for the manuscript; feel free to criticize.

ENH: first draft of abstract for SciPy paper

---

scipy-1.0/paper.tex
scipy-1.0/poly.tex
scipy-1.0/references.bib

Certainly needs to be copy-edited, can be expanded or shortened, depending on how the whole article pans out. But it's a start.

first draft of the `interpolate` subsection

---

scipy-1.0/ckdtree.tex
scipy-1.0/references.bib

It would be helpful to carefully check the literature citations (probably add more / correct ones) & perhaps add in the worst-case time complexity for the KNN algorithm. I can find a few informal derivations of this online, but I'm not convinced that I've found a published manuscript that corresponds to what was implemented in SciPy for KNN.

First draft of cKDTree KNN algorithm / tech improvement section

---

scipy-1.0/README.md

Adding the CircleCI link to a 1.0 paper specific README to make it easier to access the latest PDF built from merges into the master branch.

Added README with CircleCI badge / link for SciPy 1.0 manuscript work

---

scipy-1.0/ckdtree.tex
scipy-1.0/references.bib

Fusing the subsections in kdtree tech improvements section was briefly discussed in the BIDS sprint; also tried to add one or two more refs that might be relevant.

Fuse subsections for kdtree tech improvements; add a few refs

---

scipy-1.0/paper.tex
scipy-1.0/references.bib

May want to update/expand/remove this after seeing what gets added in the introduction part of the paper.

Add a short section on maintainers and contributors.

---

scipy-1.0/paper.tex

Update the number of public API objects from 2600 to 1500.

---

scipy-1.0/paper.tex
scipy-1.0/references.bib

Here's a little material on the Cython wrappers. I'm less familiar with the Cython wrappers for scipy.special though, so there may be more to be said about them.

Initial Draft of Section on Cython Wrappers for BLAS, LAPACK, and Special

---

scipy-1.0/paper.tex

Here's a rough draft of the section on `sparse` tech improvements over the past ~3 years. It could be pretty far off from what we want the focus to be--just intended as a catalyst for criticism / discussion, etc.

Sparse tech improvements section draft

---

scipy-1.0/ckdtree.tex
scipy-1.0/paper.tex

This is mostly cosmetic.  I used section/subsection/subsubsection consistently and wrapped all lines.  I added a fixme command and used it.  And I ran a spell checker and confirmed each change.

Consistency

---

scipy-1.0/paper.tex
scipy-1.0/references.bib

Checklist item from #65 -- cite the `asv` GitHub repo -- couldn't find any better citation source for that project.

Cite asv repo

---

scipy-1.0/paper.tex
scipy-1.0/references.bib

Checklist items from #65:
- "In addition to these longer introductory articles,"
- repeat on "In addition" from last sentence
- the tense of the prose in the first paragraph of the "SciPy Matures" subsection feels a little off

SciPy Matures paragraph tense fix & repeat removal

---

scipy-1.0/paper.tex
scipy-1.0/references.bib

For checklist item in #65:
> Backgroud: first paragraph -- one thought here: this is a scientific journal, so we could mention that Python is a dynamically typed language & also cite the most popular CPython implementation with the highly-cited Python - C API reference manual produced by Guido

More accurate description of CPython & citations

---

scipy-1.0/paper.tex
scipy-1.0/references.bib

For #65 checklist item:
> Introduction: "...a variety of social activities centered around them" (cite conferences?? it is done a bit later, but either do it first here or remove)

Add social Python citation

---

scipy-1.0/paper.tex
scipy-1.0/references.bib

Target checklist item from #65:
> Introduction: "in the first paragraph we should immediately add some kind of citation for NumPy & explain briefly what it is for the audience of the journal"

Add brief description + citation of NumPy in first paragraph of intro

---

scipy-1.0/paper.tex

I'm not sure if it belongs in Architecture and implementation choices,
but it makes more sense there than where it was.

Move project scope section

---

scipy-1.0/paper.tex

Various revisions for SciPy begins section

Scipy begins revisions

---

scipy-1.0/paper.tex

Changes suggested in #116 but not committed before merge

Test suite 2

---

scipy-1.0/paper.tex

Project organization - Governance 2

---

scipy-1.0/paper.tex
scipy-1.0/references.bib

Fixes #126 -- probably a good idea to strike while the iron is hot for this black hole project.
Core devs should feel free to write over my commits directly to improve this--I don't mind, and we suffer from reviewer bandwidth here anyway.

Cite M87 black hole project

---

scipy-1.0/ckdtree.tex

The section about cKDTree is quite long, so I thought it would be worth
mentioning what k-d trees are.

Mention what cKDTree does

---

scipy-1.0/paper.tex

Trim LowLevelCallable

---

scipy-1.0/paper.tex
scipy-1.0/subpackages.tex

Revised description of stats module

---

scipy-1.0/ckdtree.tex
scipy-1.0/paper.tex
scipy-1.0/scipy-optimize.tex
scipy-1.0/subpackages.tex

Key word being "attempt". I'm not sure if all of these changes are correct, but this will hopefully at least highlight potential misuses of the these words.
Closes #47

Attempt to make use of (sub)package/(sub)module consistent

---

scipy-1.0/paper.tex
scipy-1.0/references.bib

Added number of downloads via conda

---

scipy-1.0/paper.tex

Combine potentially redundant information about STScI transition to Python

---

scipy-1.0/ckdtree.tex
scipy-1.0/paper.tex
scipy-1.0/poly.tex

I've not finished reading the paper yet, but here are some nit picks to get started.

Grammar and other nit picks

---

scipy-1.0/paper.tex

Thanks for a wonderfully written paper! I learned a couple of things even though I try to read the release notes quite carefully! =)
The "seemed to" that I removed below should at least be changed to "seems to", but I think it's best to just remove it altogether.
Additionally, I noticed that the number of dependent repos and packages are different between the abstract and the main text (under SciPy Today). I presume the main text numbers are correct, as the abstract numbers seem very low for SciPy.

Minor language tweaks

---

scipy-1.0/paper.tex
scipy-1.0/references.bib

Updated dependent package/repo numbers and cited GitHub

---

scipy-1.0/paper.tex
scipy-1.0/references.bib

Clarify coverage numbers

---

scipy-1.0/Makefile
scipy-1.0/covlett.tex

Fixes #174 
Instructions: https://www.nature.com/srep/publish/guidelines#cover-letter
Everyone has different views on how to write these things. I probably didn't do enough to get the letter PDF to show up in CI but local `make covlett` should suffice.
TODO:

Draft of cover letter

---

scipy-1.0/paper.tex
scipy-1.0/poly.tex
scipy-1.0/references.bib
scipy-1.0/scipy-optimize.tex

Clean references

---

scipy-1.0/references.bib

Hopefully we won't be rejected based on the reference section being messy : )

Cleaned references more

---

scipy-1.0/paper.tex

SciPy provides sparse arrays -> matrices

---

scipy-1.0/paper.tex
scipy-1.0/scipy-optimize.tex

Fix formatting of Refs in Table 1

---

scipy-1.0/paper.tex

Closes #206. Please see rationale there.

Remove detail from a sentence rather than making it more complex

---

scipy-1.0/paper.tex

Closes #210 .
@charris ?
The affiliation will be added next time I generate the author list.

Fixed spatial description in project scope

---

scipy-1.0/paper.tex

I think there should not be a hyphen here, if I interpret [Rule 3 here](https://www.grammarbook.com/punctuation/hyphens.asp) correctly. (not a native speaker, though).

typo: remove hyphen

---

scipy-1.0/paper.tex
scipy-1.0/scipy-optimize.tex

@gertingold I agree with your points in #209. The third is addressed in #211. Do these changes address your concerns?
If so,
Closes #209

Address #209

---

scipy-1.0/paper.tex

Addresses https://github.com/scipy/scipy-articles/issues/226

Expand description of scikits

---

scipy-1.0/paper.tex

Remove unnecessary mention of CPython

---

scipy-1.0/paper.tex

Added date and medium to Figure 1 caption

---

scipy-1.0/paper.tex
scipy-1.0/references.bib

Fixes #229
* address *Nature Methods* reviewer comment requesting
a brief explanation of the benefits of unit testing
& test line coverage before we dive into the details
of our testing infrastructure

MAINT: reviewer comment re: test benefits

---

scipy-1.0/references.bib
scipy-1.0/subpackages.tex

Mentioned tutorials again per reviewer comment

---

scipy-1.0/paper.tex

Closes #228 
Does this sufficiently address the comment?
Do the groupings of the Fortran packages make sense?

Introduce PACKs

---

scipy-1.0/paper.tex
scipy-1.0/references.bib

Fixes #221 
I plan to do another pass on this tomorrow, but wanted to see if anyone had any feedback.

Add paragraph re: funding (w/ Stefan)

---

scipy-1.0/paper.tex

Addressed low test coverage of compiled code

---

scipy-1.0/rebuttal.tex

Fixed typo in rebuttal letter
